### ISSUE TITLE
dont work in TorBrowser

### ISSUE THREAD

**Issue by Togijak** [scakemyer/cloudhole#1]
If you try to install in TorBrowser (Firefox 38.7) from file there is a message that the plugin is broken 
![2016-03-19_022442](https://cloud.githubusercontent.com/assets/4034935/13895867/c9e5d63a-ed79-11e5-830e-1b96d1fc8017.jpg)

**Comment by scakemyer** [comment]
It requires Firefox 45 since it's a WebExtension.
