### ISSUE TITLE
Failed get Clearance

### ISSUE THREAD

**Issue by Reoldyk** [scakemyer/cloudhole#2]
Failed to get clearance from API: 404
http://isup.me/cloudhole.herokuapp.com/
![down for everyone or just me -- check if your website is down or up- 2016-05-08 18-44-17](https://cloud.githubusercontent.com/assets/4547317/15097671/fa2e3d0a-154c-11e6-853f-72ce222ceb6e.png)

FF 45.01
CloudHole 1.4.1

**Comment by scakemyer** [comment]
The API is on a free heroku plan, so it's only up 18hrs/day...
